version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ~/.composer/docker-cache/:/root/.composer
    depends_on:
      - mongodb

  web:
    image: nginx:1.17.3
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mongodb:
    image: mongo:4.2.10
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null # --quiet
